spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leegive/SpringCloud.git
          search-paths: config/repo
          username: leegive
          password: Wj173749
  rabbitmq:
    host: localhost
    username: leegive
    password: leegive
    port: 5672
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/